language: python
python:
  - "2.6"
  - "2.7"
install:
   - pip install Django==$DJANGO_VERSION --use-mirrors
   - pip install -r dev_requirements.txt --use-mirrors
   - python setup.py develop
env:
  - DJANGO_VERSION=1.4.2
  - DJANGO_VERSION=1.5.1
script: python setup.py nosetests
